### ISSUE TITLE
Hi, storage lock()

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/threadify#2]
Cool script

If called by 2 contexts it might fail due to the lock(), wont it?
But there might be little chance for that....

**Comment by hamzahik** [comment]
@vegarringdal if two threads call `lock` on the storage then there will always be one that does it first. The one that called it first will be able to continue running his code normally. The second will be paused until `unlock` is called on the first.

The worst case scenario is that no free workers are available and that the first thread needs to create one. When this happens and if the used module has an `init` defined the second thread will be paused until the `init` code is run. If we suppose the `init` takes forever and never ends, the timeout will occur (`DEFAULTS.CREATION_TIMEOUT`) and the second thread will be back to work again.

That is why the params : `CREATION_TIMEOUT` and `RESPONSE_TIMEOUT` are important. They are defined on the top of the `index.js` file so they can easily be tweaked.

**Comment by vegarringdal** [comment]
ok :-)

Im playing around with a worker storage, maybe something like that can be useful
It wont block, and you will be able to have multiple storages

it will take key (string), and value (what ever as long as JSON.stringify works

There as always a chance that what ever Im making atm will be a complete failure 😂

**Comment by hamzahik** [comment]
@vegarringdal we have a new API that will be available in the 2.1.0 release (few weaks after the 2.0.0 )
called `SharedStorage ` I think it does what you actually want :)

**Comment by vegarringdal** [comment]
Great, but Im still gonna make it, since its the best way to learn

**Comment by vegarringdal** [comment]
@hamzahik 
Here it is 😄 
https://github.com/vegarringdal/WAK-SharedStorage

**Comment by vegarringdal** [comment]
@hamzahik 
It works, is there any way I can get the name of the worker without calling it after its connected ? (in a shared worker)

**Comment by vegarringdal** [comment]
Btw, just did a few updates to results are better and clearer
What do you think ? 😄 
Anything bad, or missing?
